---

- name: Install haproxy package
  package:
    name: haproxy
    state: present

- name: Deploy haproxy configuration
  template:
    src: templates/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  tags:
    - config

- name: systemctl daemon-reload / start haproxy
  systemd:
    daemon_reload: yes
    name: haproxy
    state: restarted
    enabled: yes
